clc
clear all
close all

addpath('./PlottingShit/legendflex-pkg-master/legendflex/')
addpath('./PlottingShit/legendflex-pkg-master/setgetpos_V1.2/')


%% cell 1
figure(1);

linespec = [repmat({'r';'b';'g';'c';'m'},2,1), ...
[repmat({'-'}, 5, 1); repmat({'--'}, 5, 1)]];


x = [0 10];
y = (1:10)'*x + 10;

%% cell 3
% hln(:,1) = plot( x, y);
for k = 1:10
    hln(k,1) = semilogy( x, y(k,:),[linespec{k,1},linespec{k,2}],'LineWidth',1.5,'MarkerSize',8);hold on;
end
% set(hln(:,1), {'color','linestyle'}, linespec);

[hl(2).leg, hl(2).obj, hl(2).hout, hl(2).mout] = ...
legendflex(hln(1:5,1), {'$x^2 = 1$','$x^2 = 2$','3','4','5'}, ...
'anchor', {'nw','nw'}, ...
'buffer', [5 -5], ...
'fontsize',8, ...
'xscale',0.5, ...
'title', 'Color', ...
'interpreter','latex');

legendflex(hln([1 6],1), {'thing 1', 'thing 2'}, ...
'ref', hl(2).leg, ...
'anchor', {'ne','nw'}, ...
'buffer', [0 0], ...
'fontsize', 8', ...
'title', 'Line',...
'interpreter','latex');